steps:
  # Install dependencies


  - name: python:3.8
    entrypoint: pip
    args: ["install","--upgrade", "pip", "--user"] 
    
  - name: python:3.8
    entrypoint: pip
    args: ["install","--upgrade", "tfx[kfp]<2", "--user"] 
    
  - name: python:3.8
    entrypoint: pip
    args: ["install","-r", "requirements.txt", "--user"] 

  
  # Compile pipeline
  - name: 'python:3.8'
    entrypoint: 'python'
    args: ['tfx-pipeline.py']
    id: 'compile'

  # Upload compiled pipeline to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'uct-bigquery_pipeline.json', 'gs://dt-ml-pipeline-bucket/Pipelines_json']
    id:  'upload'
    waitFor: ['compile']
